//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner_Image_Dtl
    {
        public long BNR_Img_Id { get; set; }
        public string BNR_Image_Path { get; set; }
        public bool IsActive { get; set; }
        public int Add_user { get; set; }
        public System.DateTime Add_DateTime { get; set; }
        public int Mod_User { get; set; }
        public System.DateTime Mod_DateTime { get; set; }
    }
}
