//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KEY_Specifications
    {
        public KEY_Specifications()
        {
            this.Value_Specification = new HashSet<Value_Specification>();
        }
    
        public int spec_col_id { get; set; }
        public string spec_col_Name { get; set; }
        public int spec_cate_id { get; set; }
        public int Add_User_id { get; set; }
        public System.DateTime Add_Datetime { get; set; }
        public int Mod_User_Id { get; set; }
        public System.DateTime Modify_Datetime { get; set; }
    
        public virtual ICollection<Value_Specification> Value_Specification { get; set; }
    }
}
