//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOfferValue
    {
        public int Pid { get; set; }
        public Nullable<int> offer { get; set; }
        public Nullable<int> OfrValtype { get; set; }
    }
}
