//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrderDetail
    {
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int PDT_Id { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
