//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class ProductOrder
    {
        public ProductOrder()
        {
            this.ProductOrderDetails = new HashSet<ProductOrderDetail>();
        }

        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal Total { get; set; }
        [Required(ErrorMessage = "Please enter your Name")]
        public string Customer_name { get; set; }
        [Required(ErrorMessage = "Please enter your Address")]
        public string Customer_Address { get; set; }
        [Required(ErrorMessage = "Please enter your email id")]
        [EmailAddress]
        [Display(Name = "Email Id")]
        public string Emailid { get; set; }
        [Required(ErrorMessage = "Please enter your Mobile No")]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Entered mobile no is not valid.")]  

        [RegularExpression(@"^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$", ErrorMessage = "Entered mobile no is not valid.")]
        public string mobileNo { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Cupn_id { get; set; }

        public virtual ICollection<ProductOrderDetail> ProductOrderDetails { get; set; }
    }
}
