//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info
    {
        public int UidNo { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Mobile_number { get; set; }
        public string E_mail_id { get; set; }
        public System.DateTime DOB { get; set; }
        public string Address_Communication { get; set; }
        public string Usr_pwd { get; set; }
        public string Usr_type { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Isactive { get; set; }
    }
}
