//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KJGarmentsWeb.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Value_Specification
    {
        public int Spec_value_id { get; set; }
        public int Key_spec_id { get; set; }
        public string key_Col_Value { get; set; }
        public int Product_id { get; set; }
        public Nullable<int> AddUser_id { get; set; }
        public Nullable<System.DateTime> Add_Datetime { get; set; }
        public Nullable<int> mod_user_Id { get; set; }
        public Nullable<System.DateTime> Mod_Datetime { get; set; }
    
        public virtual KEY_Specifications KEY_Specifications { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
